server:
  port: 8081
  servlet:
    context-path: /store

spring:
  elasticsearch:
    uris: http://localhost:9200 # Địa chỉ server Elasticsearch của bạn
  datasource:
    url: "jdbc:mysql://localhost:3306/bookstore"
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
      order_inserts: true
      order_updates: true
      format_sql: true
    show-sql: true


jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 1000000
  refreshable-duration: 10000